### ISSUE TITLE
Bad call: specified package io.appium.uiautomator2.server.test 

### ISSUE THREAD

**Issue by hadilq** [appium/appium-uiautomator2-server#192]
In our acceptance tests we randomly encounter the following exception. After appium has crashed, our app crashed too. 

```
09-25 12:40:02.745  1000  1604  1667 D VoldConnector: RCV <- {200 44 Command succeeded}
09-25 12:40:02.792  1000  1604  1604 I Telecom : DefaultDialerCache: Refreshing default dialer for user 0: now com.google.android.dialer: DDC.oR@AP8
09-25 12:40:02.836  1000  1604  5690 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.sheypoor.mobile.debug flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher
09-25 12:40:03.024  1000  1604  1826 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10080 user=0: from pid 9675
09-25 12:40:03.380  1000  1604  1826 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10080 user=0: start instr
09-25 12:40:03.391  1000  1604  1826 I ActivityManager: Start proc 9687:io.appium.uiautomator2.server/u0a80 for added application io.appium.uiautomator2.server
09-25 12:40:05.473  1000  1604  1826 W AppOps  : Bad call: specified package io.appium.uiautomator2.server.test under uid 10080 but it is really 10081
09-25 12:40:05.473  1000  1604  1826 W AppOps  : java.lang.RuntimeException: here
09-25 12:40:05.473  1000  1604  1826 W AppOps  : 	at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1322)
09-25 12:40:05.473  1000  1604  1826 W AppOps  : 	at com.android.server.AppOpsService.startOperation(AppOpsService.java:1143)
09-25 12:40:05.473  1000  1604  1826 W AppOps  : 	at com.android.server.power.Notifier.onWakeLockAcquired(Notifier.java:189)
09-25 12:40:05.473  1000  1604  1826 W AppOps  : 	at com.android.server.power.PowerManagerService.notifyWakeLockAcquiredLocked(PowerManagerService.java:1230)
09-25 12:40:05.473  1000  1604  1826 W AppOps  : 	at com.android.server.power.PowerManagerService.acquireWakeLockInternal(PowerManagerService.java:1087)
09-25 12:40:05.473  1000  1604  1826 W AppOps  : 	at com.android.server.power.PowerManagerService.-wrap7(Unknown Source:0)
09-25 12:40:05.473  1000  1604  1826 W AppOps  : 	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4166)
09-25 12:40:05.473  1000  1604  1826 W AppOps  : 	at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:66)
09-25 12:40:05.473  1000  1604  1826 W AppOps  : 	at android.os.Binder.execTransact(Binder.java:697)
```

Is there anything that we can do to fix it?

**Comment by mehrdad-abdoli** [comment]
appium 1.9.0
android 8.1

**Comment by v3g3t4x** [comment]
Which is the solution ? we have the same issue

**Comment by josh-strickland-4c** [comment]
I also have hit this on 
Appium v1.9.1
UI Automator 2
Android Os v9

**Relevant appium server logs:**
`[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'`

**Relevant device logs:**
`2018-11-21 11:43:53.229 903-19665/? W/AppOps: Bad call: specified package io.appium.uiautomator2.server.test under uid 10005 but it is really 10019
    java.lang.RuntimeException: here
        at com.android.server.AppOpsService.getOpsRawLocked(AppOpsService.java:1986)
        at com.android.server.AppOpsService.getOpLocked(AppOpsService.java:2019)
        at com.android.server.AppOpsService.finishOperation(AppOpsService.java:1750)
        at android.app.AppOpsManager.finishOp(AppOpsManager.java:2536)
        at com.android.server.power.Notifier.onWakeLockReleased(Notifier.java:316)
        at com.android.server.power.PowerManagerService.notifyWakeLockReleasedLocked(PowerManagerService.java:1219)
        at com.android.server.power.PowerManagerService.removeWakeLockLocked(PowerManagerService.java:1103)
        at com.android.server.power.PowerManagerService.releaseWakeLockInternal(PowerManagerService.java:1075)
        at com.android.server.power.PowerManagerService.access$3500(PowerManagerService.java:116)
        at com.android.server.power.PowerManagerService$BinderService.releaseWakeLock(PowerManagerService.java:4180)
        at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:95)
        at android.os.Binder.execTransact(Binder.java:731)
2018-11-21 11:43:53.230 31559-31658/io.appium.uiautomator2.server I/appium: Stopping uiautomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server
`

Not sure how to go about solving this

**Comment by nateridderman** [comment]
I'm seeing this as well. Appium 1.9.1

**Comment by sshock** [comment]
fyi, in my case this turned out to be a red herring; the real problem was somewhere else, so maybe this is just a spurious message that can be safely ignored...
