### ISSUE TITLE
Version v4.5.0 is incompatible with devices that do not have BluetoothAdapter.nameForState method

### ISSUE THREAD

**Issue by anorimaki** [appium/appium-uiautomator2-server#314]
After upgrading to v4.5.0 I get this log in Appium. It seems that this device has an old implementation of BluetoothAdapter where this method is missing.
With version v4.4.0 I don't have this problem.

```
[debug] [ADB] Running '/Users/mobile/Library/Android/sdk/platform-tools/adb -P 5037 -s ZX1D236ZPL forward --remove tcp\:8207'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1575018651939 (10:10:51 GMT+0100 (Central European Standard Time))
[debug] [W3C] Encountered internal error running command: An unknown server-side error occurred while processing the command. Original error: error while getting method nameForState from class class android.bluetooth.BluetoothAdapter with parameter types [int]
[debug] [W3C] io.appium.uiautomator2.common.exceptions.UiAutomator2Exception: error while getting method nameForState from class class android.bluetooth.BluetoothAdapter with parameter types [int]
[debug] [W3C]   at io.appium.uiautomator2.utils.ReflectionUtils.method(ReflectionUtils.java:86)
[debug] [W3C]   at io.appium.uiautomator2.handler.GetDeviceInfo.extractBluetoothInfo(GetDeviceInfo.java:104)
[debug] [W3C]   at io.appium.uiautomator2.handler.GetDeviceInfo.safeHandle(GetDeviceInfo.java:127)
[debug] [W3C]   at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)
[debug] [W3C]   at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)
[debug] [W3C]   at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)
[debug] [W3C]   at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:51)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C]   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C]   at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
[debug] [W3C]   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
[debug] [W3C]   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
[debug] [W3C]   at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
[debug] [W3C]   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
[debug] [W3C]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
[debug] [W3C]   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[debug] [W3C]   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
[debug] [W3C]   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
[debug] [W3C]   at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
[debug] [W3C]   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
[debug] [W3C]   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
[debug] [W3C]   at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
[debug] [W3C]   at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[debug] [W3C]   at java.lang.Thread.run(Thread.java:818)
[debug] [W3C] Caused by: java.lang.NoSuchMethodException: nameForState [int]
[debug] [W3C]   at java.lang.Class.getMethod(Class.java:624)
[debug] [W3C]   at java.lang.Class.getDeclaredMethod(Class.java:586)
[debug] [W3C]   at io.appium.uiautomator2.utils.ReflectionUtils.method(ReflectionUtils.java:80)
[debug] [W3C]   ... 32 more
[debug] [W3C]

```

**Comment by mykola-mokhnach** [comment]
Thanks for the report. It seems like the method does not exist for all APIs. I'll provide a patch today

**Comment by anorimaki** [comment]
Thank you for your quick answer @mykola-mokhnach
