### ISSUE TITLE
Unable to change orientation

### ISSUE THREAD

**Issue by manjula-balamurugan** [appium/appium-uiautomator2-server#443]
set auto screen rotate to OFF in my android device. But when I run Appium automation, it gets set to ON somehow. Is there a way to prevent Appium from setting auto screen rotate to ON?

 An unknown server-side error occurred while processing the command. Original error: Set the orientation, but app refused to rotate. (Selenium::WebDriver::Error::UnknownError)
      UnknownError: An unknown server-side error occurred while processing the command. Original error: Set the orientation, but app refused to rotate.
@ruby @appium

**Comment by KazuCocoa** [comment]
What device did you use and could you share the logcat?

> set auto screen rotate to OFF in my android device. But when I run Appium automation, it gets set to ON somehow. Is there a way to prevent Appium from setting auto screen rotate to ON?

I haven't seen such behaviors in my experience. Perhaps your device and logcat may help to see some behaviors.

**Comment by manjula-balamurugan** [comment]
Device: redmi 9
os: 1

https://user-images.githubusercontent.com/89239421/135954130-1e508bce-b317-4185-9003-7d938f0dd073.mp4

0
Watch Video at 01.09 minute,Its rotating but just for a second.how to work on it in browser stack?

  expected: "landscape"
           got: "portrait"
      
      (compared using ==)
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/video_steps.rb:144:in `"I change phone orientation to landscape mode"'
      features/Video.feature:260:in `When I change phone orientation to landscape mode'
[cucumber]
  Scenario failure on features/Video.feature:255
  at 8:38:36 AM on Oct 5, 2021!
  Full backtrace:
  /var/lib/gems/2.7.0/gems/rspec-support-3.6.0/lib/rspec/support.rb:87:in `block in <module:Support>'
  /var/lib/gems/2.7.0/gems/rspec-support-3.6.0/lib/rspec/support.rb:96:in `notify_failure'
  /var/lib/gems/2.7.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
  /var/lib/gems/2.7.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
  /var/lib/gems/2.7.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
  /var/lib/gems/2.7.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
  /var/lib/gems/2.7.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
  /var/lib/gems/2.7.0/gems/rspec-expectations-3.6.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
  /home/manjula.balamurugan/discovery-appium_OLD/atve/atve_android_old/features/step_definitions/video_steps.rb:144:in `"I change phone orientation to landscape mode"'
  features/Video.feature:260:in `When I change phone orientation to landscape mode'
Fetching public url from Browserstack

Failing Scenarios:
cucumber features/Video.feature:255 # Scenario: Verify user should be able to switch to landscape orientation while playing any content

1 scenario (1 failed)
4 steps (1 failed, 3 passed)
1m46.182s
/var/lib/gems/2.7.0/gems/cucumber-core-3.2.1/lib/cucumber/core/test/result.rb:12: warning: calling private without arguments inside a method may not have the intended effect
(Dont know how to get a log)

**Comment by manjula-balamurugan** [comment]
**2.Running scripts on Emulator**

Given I login as anonymous user
When I am on video landing screen 
And video plays in portrait mode by default
When I change phone orientation to landscape mode  #####(Unable to rotate the phone )

Error:

Screen rotation cannot be changed to ROTATION_270 after 2000ms. Is it locked programmatically? (Selenium::WebDriver::Error::ElementNotInteractableError)
      io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Screen rotation cannot be changed to ROTATION_270 after 2000ms. Is it locked programmatically?
        at io.appium.uiautomator2.model.internal.CustomUiDevice.setRotationSync(CustomUiDevice.java:203)
        at io.appium.uiautomator2.handler.SetOrientation.safeHandle(SetOrientation.java:41)
        at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
        at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:262)
        at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:256)
        at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:923)
      ./features/step_definitions/video_steps.rb:140:in `"I change phone orientation to landscape mode"'
      features/Video.feature:260:in `When I change phone orientation to landscape mode'
[cucumber]
  Scenario failure on features/Video.feature:255
  at 9:01:15 AM on Oct 5, 2021!
  Full backtrace:
  io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Screen rotation cannot be changed to ROTATION_270 after 2000ms. Is it locked programmatically?
        at io.appium.uiautomator2.model.internal.CustomUiDevice.setRotationSync(CustomUiDevice.java:203)
        at io.appium.uiautomator2.handler.SetOrientation.safeHandle(SetOrientation.java:41)
        at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:41)
        at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:262)
        at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:256)
        at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:923)
  /var/lib/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
  /var/lib/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
  /var/lib/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
  /var/lib/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
  /var/lib/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
  /var/lib/gems/2.7.0/gems/appium_lib_core-4.7.0/lib/appium_lib_core/common/base/http_default.rb:97:in `call'
  /var/lib/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
  /var/lib/gems/2.7.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
  /var/lib/gems/2.7.0/gems/appium_lib_core-4.7.0/lib/appium_lib_core/common/device/orientation.rb:21:in `screen_orientation='
  /var/lib/gems/2.7.0/gems/appium_lib_core-4.7.0/lib/appium_lib_core/common/base/rotable.rb:36:in `rotation='
  /home/manjula.balamurugan/discovery-appium_OLD/atve/atve_android_old/features/step_definitions/video_steps.rb:140:in `"I change phone orientation to landscape mode"'
  features/Video.feature:260:in `When I change phone orientation to landscape mode'

Failing Scenarios:
cucumber features/Video.feature:255 # Scenario: Verify user should be able to switch to landscape orientation while playing any content

1 scenario (1 failed)
4 steps (1 failed, 3 passed)
0m52.547s
/var/lib/gems/2.7.0/gems/cucumber-core-3.2.1/lib/cucumber/core/test/result.rb:12: warning: calling private without arguments inside a method may not have the intended effect
Stopping Appium Server
node: no process found

**Comment by manjula-balamurugan** [comment]
**3.Running same script on Real Device(Redmi 9)**

Error 1:
 Screen rotation cannot be changed to ROTATION_270 after 2000ms. Is it locked programmatically? (Selenium::WebDriver::Error::ElementNotInteractableError)
      io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Screen rotation cannot be changed to ROTATION_270 after 2000ms. Is it locked programmatically?


Error 2:
 Screen rotation cannot be changed to ROTATION_270 after 2000ms. Is it locked programmatically? (Selenium::WebDriver::Error::ElementNotInteractableError)
      io.appium.uiautomator2.common.exceptions.InvalidElementStateException: Screen rotation cannot be changed to ROTATION_270 after 2000ms. Is it locked programmatically?

**Comment by KazuCocoa** [comment]
I don't have Redmi 9, but found its 8. It worked the orientation command on my env.
It did not automatically turn on the auto orientation.

> For browser stack

Then please ask for their support first. Potentially their environment has some limitations.

> Original error: Set the orientation, but app refused to rotate.

https://stackoverflow.com/questions/39387158/i-am-getting-error-while-trying-to-check-orientation-of-app said the case could happen when the app refused to orientation or it depends on the sensor.
