### ISSUE TITLE
Appium-uiautomator2-server reports INSTRUMENTATION_FAILED errors on Android 11

### ISSUE THREAD

**Issue by dongjinhai** [appium/appium-uiautomator2-server#469]
I used Appium to test Android 11 devices.
Appium - desktop: 1.22.0
Appium - python - client: 2.0.0
I copy the command to the terminal to execute, and the output is as follows
![image](https://user-images.githubusercontent.com/18241524/168415032-27184689-419a-40de-9df9-49d71c70355b.png)

The appium-Desktop logs are as follows
```
[info] [35m[HTTP][39m Waiting until the server is closed
[info] [35m[HTTP][39m Received server close event
[info] [35m[Appium][39m Welcome to Appium v1.22.0
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 0.0.0.0:4723[debug] [35m[HTTP][39m Request idempotency key: b7701406-c7f7-4741-b221-2bde04fd4c6f
[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"11","appium:deviceName":"hongmo3","appium:appPackage":"tv.danmaku.bili","appium:appActivity":".MainActivityV2","appium:unicodeKeyboard":true,"appium:resetKeyboard":true,"appium:noReset":true,"appium:newCommandTimeout":"6000","appium:automationName":"UiAutomator2"},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","platformVersion":"11","deviceName":"hongmo3","appPackage":"tv.danmaku.bili","appActivity":".MainActivityV2","unicodeKeyboard":true,"resetKeyboard":true,"noReset":true,"newCommandTimeout":"6000","automationName":"UiAutomator2"}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"platformName":"Android","platformVersion":"11","deviceName":"hongmo3","appPackage":"tv.danmaku.bili","appActivity":".MainActivityV2","unicodeKeyboard":true,"resetKeyboard":true,"noReset":true,"newCommandTimeout":"6000","automationName":"UiAutomator2"},null,{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"11","appium:deviceName":"hongmo3","appium:appPackage":"tv.danmaku.bili","appium:appActivity":".MainActivityV2","appium:unicodeKeyboard":true,"appium:resetKeyboard":true,"appium:noReset":true,"appium:newCommandTimeout":"6000","appium:automationName":"UiAutomator2"},"firstMatch":[{}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1652511471850 (14:57:51 GMT+0800 (中国标准时间))
[warn] [35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[info] [35m[Appium][39m Appium v1.22.0 creating new AndroidUiautomator2Driver (v1.69.0) session
[info] [35m[Appium][39m Applying relaxed security to 'AndroidUiautomator2Driver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
[debug] [35m[BaseDriver][39m W3C capabilities and MJSONWP desired capabilities were provided
[debug] [35m[BaseDriver][39m Creating session with W3C capabilities: {
[debug] [35m[BaseDriver][39m   "alwaysMatch": {
[debug] [35m[BaseDriver][39m     "platformName": "Android",
[debug] [35m[BaseDriver][39m     "appium:platformVersion": "11",
[debug] [35m[BaseDriver][39m     "appium:deviceName": "hongmo3",
[debug] [35m[BaseDriver][39m     "appium:appPackage": "tv.danmaku.bili",
[debug] [35m[BaseDriver][39m     "appium:appActivity": ".MainActivityV2",
[debug] [35m[BaseDriver][39m     "appium:unicodeKeyboard": true,
[debug] [35m[BaseDriver][39m     "appium:resetKeyboard": true,
[debug] [35m[BaseDriver][39m     "appium:noReset": true,
[debug] [35m[BaseDriver][39m     "appium:newCommandTimeout": "6000",
[debug] [35m[BaseDriver][39m     "appium:automationName": "UiAutomator2"
[debug] [35m[BaseDriver][39m   },
[debug] [35m[BaseDriver][39m   "firstMatch": [
[debug] [35m[BaseDriver][39m     {}
[debug] [35m[BaseDriver][39m   ]
[debug] [35m[BaseDriver][39m }
[warn] [35m[BaseDriver][39m Number capability passed in as string. Functionality may be compromised.
[warn] [35m[BaseDriver][39m Capability 'newCommandTimeout' changed from string ('6000') to integer (6000). This may cause unexpected behavior
[info] [35m[BaseDriver][39m Session created with session id: 7db3c3cf-6956-4986-ae58-6702fa72d15d
[info] [35m[UiAutomator2][39m Starting 'tv.danmaku.bili' directly on the device
[info] [35m[ADB][39m Using 'adb.exe' from 'E:\AndroidSDK\platform-tools\adb.exe'
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 start-server'
[info] [35m[AndroidDriver][39m Retrieving device list
[debug] [35m[ADB][39m Trying to find a connected android device
[debug] [35m[ADB][39m Getting connected devices[debug] [35m[ADB][39m Connected devices: [{"udid":"1a492309","state":"device"}]
[info] [35m[AndroidDriver][39m Looking for a device with Android '11.0.0'
[debug] [35m[ADB][39m Setting device id to 1a492309
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell getprop ro.build.version.release'
[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 11
[info] [35m[AndroidDriver][39m Using device: 1a492309
[info] [35m[ADB][39m Using 'adb.exe' from 'E:\AndroidSDK\platform-tools\adb.exe'
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 start-server'
[debug] [35m[ADB][39m Setting device id to 1a492309
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell getprop ro.build.version.sdk'[debug] [35m[ADB][39m Current device property 'ro.build.version.sdk': 30
[info] [35m[ADB][39m Getting device platform version
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell getprop ro.build.version.release'
[debug] [35m[ADB][39m Current device property 'ro.build.version.release': 11
[debug] [35m[ADB][39m Device API level: 30
[info] [35m[UiAutomator2][39m Relaxing hidden api policy
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''[warn] [35m[AndroidDriver][39m No app sent in, not parsing package/activity
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 wait-for-device'
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell echo ping'[debug] [35m[AndroidDriver][39m Pushing settings apk to device...
[debug] [35m[ADB][39m Getting install status for io.appium.settings
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell dumpsys package io.appium.settings'
[debug] [35m[ADB][39m 'io.appium.settings' is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.settings'
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell dumpsys package io.appium.settings'[debug] [35m[ADB][39m The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('3.4.0' >= '3.4.0')
[debug] [35m[ADB][39m There is no need to install/upgrade 'C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[debug] [35m[ADB][39m Getting IDs of all 'io.appium.settings' processes
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell 'pgrep --help; echo $?''
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell pgrep -f \(\[\[:blank:\]\]\|\^\)io\.appium\.settings\(\[\[:blank:\]\]\|\$\)'[debug] [35m[AndroidDriver][39m io.appium.settings is already running. There is no need to reset its permissions.
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell appops set io.appium.settings android:mock_location allow'
[debug] [35m[Logcat][39m Starting logs capture with command: E:\\AndroidSDK\\platform-tools\\adb.exe -P 5037 -s 1a492309 logcat -v threadtime[debug] [35m[AndroidDriver][39m Enabling Unicode keyboard support
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell settings get secure default_input_method'
[debug] [35m[AndroidDriver][39m Unsetting previous IME com.sohu.inputmethod.sogou.nubia/.SogouIME
[debug] [35m[AndroidDriver][39m Setting IME to 'io.appium.settings/.UnicodeIME'
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell ime enable io.appium.settings/.UnicodeIME'[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell ime set io.appium.settings/.UnicodeIME'[debug] [35m[UiAutomator2][39m Forwarding UiAutomator2 Server port 6790 to local port 8200[debug] [35m[ADB][39m Forwarding system: 8200 to device: 6790
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 forward tcp:8200 tcp:6790'[debug] [35m[ADB][39m Getting install status for io.appium.uiautomator2.server
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell dumpsys package io.appium.uiautomator2.server'
[debug] [35m[ADB][39m 'io.appium.uiautomator2.server' is installed
[debug] [35m[ADB][39m Getting package info for 'io.appium.uiautomator2.server'
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell dumpsys package io.appium.uiautomator2.server'[debug] [35m[ADB][39m The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('4.24.0' >= '4.24.0')
[debug] [35m[UiAutomator2][39m io.appium.uiautomator2.server installation state: sameVersionInstalled
[debug] [35m[ADB][39m Checking app cert for C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.24.0.apk
[debug] [35m[ADB][39m Using the previously cached signature entry for 'appium-uiautomator2-server-v4.24.0.apk'
[debug] [35m[ADB][39m sha256 hash did match for 'appium-uiautomator2-server-v4.24.0.apk'
[debug] [35m[ADB][39m Getting install status for io.appium.uiautomator2.server.test
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell dumpsys package io.appium.uiautomator2.server.test'
[debug] [35m[ADB][39m 'io.appium.uiautomator2.server.test' is installed
[debug] [35m[ADB][39m Checking app cert for C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[debug] [35m[ADB][39m Using the previously cached signature entry for 'appium-uiautomator2-server-debug-androidTest.apk'
[debug] [35m[ADB][39m sha256 hash did match for 'appium-uiautomator2-server-debug-androidTest.apk'
[info] [35m[UiAutomator2][39m Server packages are not going to be (re)installed
[debug] [35m[UiAutomator2][39m Waiting up to 30000ms for services to be available
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell pm list instrumentation'[debug] [35m[UiAutomator2][39m Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[info] [35m[ADB][39m Adding packages ["io.appium.settings","io.appium.uiautomator2.server","io.appium.uiautomator2.server.test"] to Doze whitelist
[debug] [35m[ADB][39m Got the following command chunks to execute: [["dumpsys","deviceidle","whitelist","+io.appium.settings",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server.test",";"]]
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell dumpsys deviceidle whitelist +io.appium.settings ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server.test ;'[debug] [35m[UiAutomator2][39m No app capability. Assuming it is already on the device
[debug] [35m[UiAutomator2][39m Performing shallow cleanup of automation leftovers
[debug] [35m[UiAutomator2][39m No obsolete sessions have been detected (socket hang up)
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell am force-stop io.appium.uiautomator2.server.test'
[info] [35m[UiAutomator2][39m Starting UIAutomator2 server 4.24.0
[info] [35m[UiAutomator2][39m Using UIAutomator2 server from 'C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.24.0.apk' and test from 'C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
[info] [35m[UiAutomator2][39m Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [35m[ADB][39m Creating ADB subprocess with args: ["-P",5037,"-s","1a492309","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"][info] [35m[WD Proxy][39m socket hang up
[debug] [35m[Instrumentation][39m android.util.AndroidException: INSTRUMENTATION_FAILED: io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner[debug] [35m[Instrumentation][39m The process has exited with code 1[warn] [35m[UiAutomator2][39m The instrumentation process has been unexpectedly terminated. Retrying UiAutomator2 startup (#1 of 1)
[debug] [35m[UiAutomator2][39m Performing strict cleanup of automation leftovers
[debug] [35m[UiAutomator2][39m No obsolete sessions have been detected (socket hang up)
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell am force-stop io.appium.uiautomator2.server.test'
[debug] [35m[ADB][39m Attempting to kill all uiautomator processes
[debug] [35m[ADB][39m Getting IDs of all 'uiautomator' processes
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell pgrep -f \(\[\[:blank:\]\]\|\^\)uiautomator\(\[\[:blank:\]\]\|\$\)'[info] [35m[ADB][39m No 'uiautomator' process has been found[info] [35m[UiAutomator2][39m Waiting up to 30000ms for UiAutomator2 to be online...
[debug] [35m[ADB][39m Creating ADB subprocess with args: ["-P",5037,"-s","1a492309","shell","am","instrument","-w","-e","disableAnalytics",true,"io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner"]
[debug] [35m[WD Proxy][39m Matched '/status' to command name 'getStatus'
[debug] [35m[WD Proxy][39m Proxying [GET /status] to [GET http://127.0.0.1:8200/wd/hub/status] with no body
[info] [35m[WD Proxy][39m socket hang up[debug] [35m[Instrumentation][39m android.util.AndroidException: INSTRUMENTATION_FAILED: io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner
[debug] [35m[Instrumentation][39m 	at com.android.commands.am.Instrument.run(Instrument.java:519)
[debug] [35m[Instrumentation][39m at com.android.commands.am.Am.runInstrument(Am.java:202)
[debug] [35m[Instrumentation][39m 	at com.android.commands.am.Am.onRun(Am.java:80)
[debug] [35m[Instrumentation][39m 	at com.android.internal.os.BaseCommand.run(BaseCommand.java:60)
[debug] [35m[Instrumentation][39m 	at com.android.commands.am.Am.main(Am.java:50)
[debug] [35m[Instrumentation][39m 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[debug] [35m[Instrumentation][39m 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:419)
[debug] [35m[Instrumentation][39m The process has exited with code 1[error] [35m[UiAutomator2][39m The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 session
[debug] [35m[UiAutomator2][39m Deleting UiAutomator2 server session
[warn] [35m[UiAutomator2][39m Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'DELETE /' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[debug] [35m[UiAutomator2][39m Resetting IME to 'com.sohu.inputmethod.sogou.nubia/.SogouIME'
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell ime set com.sohu.inputmethod.sogou.nubia/.SogouIME'
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell am force-stop tv.danmaku.bili'[debug] [35m[Logcat][39m Stopping logcat capture
[debug] [35m[ADB][39m Removing forwarded port socket connection: 8200 
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 forward --remove tcp:8200'
[info] [35m[UiAutomator2][39m Restoring hidden api policy to the device default configuration
[debug] [35m[ADB][39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1652511481850 (14:58:01 GMT+0800 (中国标准时间))
[debug] [35m[W3C][39m Encountered internal error running command: Error: The instrumentation process cannot be initialized. Make sure the application under test does not crash and investigate the logcat output.
[debug] [35m[W3C][39m     at Object.errorAndThrow (C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-support\lib\logging.js:94:35)
[debug] [35m[W3C][39m     at UiAutomator2Server.startSession (C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:247:13)
[debug] [35m[W3C][39m     at AndroidUiautomator2Driver.startUiAutomator2Session (C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:416:5)
[debug] [35m[W3C][39m     at AndroidUiautomator2Driver.createSession (C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:229:7)
[debug] [35m[W3C][39m     at AppiumDriver.createSession (C:\Program Files\Appium Server GUI\resources\app\node_modules\appium\lib\appium.js:387:35)
[info] [35m[HTTP][39m [37m<-- POST /wd/hub/session [39m[31m500[39m [90m10002 ms - 861[39m
[info] [35m[HTTP][39m [90m[39m
```
How can I solve this problem? Or is this a compatibility issue?

**Comment by KazuCocoa** [comment]
Could you share the logcat?

**Comment by dongjinhai** [comment]
> 

Thank you for your reply. The problem has been solved. Here's a solution.
I compared the normal log with the abnormal log, and found that the abnormal log was printed
```
[debug] �[35m[ADB]�[39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell pm list instrumentation'[debug] �[35m[UiAutomator2]�[39m Instrumentation target 'io.appium.uiautomator2.server.test/androidx.test.runner.AndroidJUnitRunner' is available
[info] �[35m[ADB]�[39m Adding packages ["io.appium.settings","io.appium.uiautomator2.server","io.appium.uiautomator2.server.test"] to Doze whitelist
[debug] �[35m[ADB]�[39m Got the following command chunks to execute: [["dumpsys","deviceidle","whitelist","+io.appium.settings",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server",";","dumpsys","deviceidle","whitelist","+io.appium.uiautomator2.server.test",";"]]
[debug] �[35m[ADB]�[39m Running 'E:\AndroidSDK\platform-tools\adb.exe -P 5037 -s 1a492309 shell dumpsys deviceidle whitelist +io.appium.settings ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server ; dumpsys deviceidle whitelist +io.appium.uiautomator2.server.test ;'[debug] �[35m[UiAutomator2]�[39m No app capability. Assuming it is already on the device
```
The key information is
```
No app capability. Assuming it is already on the device
```
Then I manually set it in the phone to allow ["io.appium.settings","io.appium.uiautomator2.server","io.appium.uiautomator2.server.test"] to start by itself, and **finally the problem was solved**
