### ISSUE TITLE
Occasionally seeing error of An unknown server-side error occurred while processing the command when start An unknown server-side error occurred while processing the command when staring android driver

### ISSUE THREAD

**Issue by Cecilia656611** [appium/appium-uiautomator2-server#494]
`2022-12-16 17:49:33.668 DEBUG device-1/DefaultSummaryPrinter: org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command 'D:\\java\\jdk\\bin\\java.exe -jar C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.12.2.apk --override' exited with code 1
2022-12-16 17:49:33.668 DEBUG device-1/DefaultSummaryPrinter: Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
2022-12-16 17:49:33.669 DEBUG device-1/DefaultSummaryPrinter: System info: host: 'xxxx', ip: 'xxxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_333'
2022-12-16 17:49:33.669 DEBUG device-1/DefaultSummaryPrinter: Driver info: driver.version: AndroidDriver
2022-12-16 17:49:33.669 DEBUG device-1/DefaultSummaryPrinter: remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not sign with default certificate. Original error Command 'D:\\java\\jdk\\bin\\java.exe -jar C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-adb\\jars\\sign.jar C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v4.12.2.apk --override' exited with code 1
2022-12-16 17:49:33.669 DEBUG device-1/DefaultSummaryPrinter:     at getResponseForW3CError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:804:9)
2022-12-16 17:49:33.669 DEBUG device-1/DefaultSummaryPrinter:     at asyncHandler (C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:381:37)`

I don't think there's a permission issue, since 2 apks under \appium-uiautomator2-server\apks are accessible to all user on the computer.
And this issue starting to emerge from last week, 5 failures out of 10 times, I'm very new to Appium and mobile automation, somebody please help, thanks a lot!!!

**Comment by KazuCocoa** [comment]
Could you report it from https://github.com/appium/appium/issues/new/choose with the appium server logs and probably with adb logs? Maybe it is easier to track in your case
