### ISSUE TITLE
Appium reports "InvalidArgumentException: Exception while reading JSON" instead of a real error

### ISSUE THREAD

**Issue by asolntsev** [appium/appium-uiautomator2-server#520]
I am running Appium **2.0.0-rc.4**.

In Java code, I am trying to click the element:
```java
new Actions(webdriver).moveToElement(element).click().perform();
```

On Java side, I get a meaningless error:
```java
InvalidArgumentException: Exception while reading JSON
```

Though in Appium server logs, I see that the real cause is:
```java
ActionsParseException: The first item of action 'default mouse' cannot define HOVER move, because its start coordinates are not set
```

### Appium stacktrace:
```java
Encountered internal error running command: io.appium.uiautomator2.common.exceptions.InvalidArgumentException: Exception while reading JSON
	at io.appium.uiautomator2.handler.W3CActions.safeHandle(W3CActions.java:92)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:277)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:271)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
  ...
Caused by: io.appium.uiautomator2.utils.w3c.ActionsParseException: The first item of action 'default mouse' cannot define HOVER move, because its start coordinates are not set
	at io.appium.uiautomator2.utils.w3c.ActionsTokenizer.extractCoordinates(ActionsTokenizer.java:252)
	at io.appium.uiautomator2.utils.w3c.ActionsTokenizer.applyPointerActionToEventsMapping(ActionsTokenizer.java:496)
	at io.appium.uiautomator2.utils.w3c.ActionsTokenizer.tokenize(ActionsTokenizer.java:575)
	at io.appium.uiautomator2.handler.W3CActions.safeHandle(W3CActions.java:83)
	... 34 more
```

### REQUEST:
Whatever this real error means, I want to see in on Java side too - instead of meaningless "Exception while reading JSON".

**Comment by KazuCocoa** [comment]
What version of UIA 2 driver did you use? Could you share the full appium log as well?
`2.29.2` is current latest driver version.

**Comment by asolntsev** [comment]
Thank you for the hint. I was using UIA 2.29.1.
After explicitly upgrading to 2.29.2, the problem disappeared.

BUT

This issue is not about an invalid version, but about **reporting the real problem** instead of "Exception while reading JSON".

**Comment by KazuCocoa** [comment]
Did you check an error message with 2.29.1 as well? I don't have running env right now, but I think https://github.com/appium/appium-uiautomator2-server/pull/522 (included in the 2.29.2) changed the error message as well

**Comment by asolntsev** [comment]
I cannot check if the error message is still incorrect (because that error doesn't happen anymore in 2.29.2). :(

**Comment by KazuCocoa** [comment]
I see. Perhaps you could use the latest for a while and check the error next time

**Comment by KazuCocoa** [comment]
Lets open a new issue if needed as ^
