### ISSUE TITLE
Cannot click an element

### ISSUE THREAD

**Issue by asolntsev** [appium/appium-uiautomator2-server#521]
In Java code, I am trying to click the element:

```java
new Actions(webdriver).moveToElement(element).click().perform();
```

This operation fails. The reason in Appium logs says:

```java
io.appium.uiautomator2.utils.w3c.ActionsParseException: The first item of action 'default mouse' cannot define HOVER move, because its start coordinates are not set
	at io.appium.uiautomator2.utils.w3c.ActionsTokenizer.extractCoordinates(ActionsTokenizer.java:252)
	at io.appium.uiautomator2.utils.w3c.ActionsTokenizer.applyPointerActionToEventsMapping(ActionsTokenizer.java:496)
	at io.appium.uiautomator2.utils.w3c.ActionsTokenizer.tokenize(ActionsTokenizer.java:575)
	at io.appium.uiautomator2.handler.W3CActions.safeHandle(W3CActions.java:83)
	... 34 more
```

### Appium logs

1. Appium request:
```
Proxying [POST /actions] to [POST http://127.0.0.1:8200/session/ea886bb4-85bc-45ff-be53-9ccf77a463fa/actions] with body: {"actions":[{"id":"default mouse","type":"pointer","parameters":{"pointerType":"touch"},"actions":[{"duration":100,"x":0,"y":0,"type":"pointerMove","origin":{"ELEMENT":"00000000-0000-0ce4-ffff-ffff00000011","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-0ce4-ffff-ffff00000011"}},{"duration":200,"x":3,"y":-3,"type":"pointerMove","origin":"pointer"},{"button":0,"type":"pointerDown"},{"button":0,"type":"pointerUp"}]}]}
```

2. Appium response:
```
Got response with status 400: {"sessionId":"ea886bb4-85bc-45ff-be53-9ccf77a463fa","value":{"error":"invalid argument","message":"Exception while reading JSON","stacktrace":"io.appium.uiautomator2.common.exceptions.InvalidArgumentException: Exception while reading JSON......
```

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-server/issues/520
