### ISSUE TITLE
Issue in finding element using findElementByAndroidUIAutomator with uiautomator2

### ISSUE THREAD

**Issue by PavithraNavaneeth** [appium/appium-uiautomator2-server#60]
Hi there,
I am finding issue in finding elements using uiautomator after upgrading to appium 1.6+ version with uiautomator2 capabilities.

Please find the details below:
**Appium Version:** 1.6.5 (installed via npm)
**Applium java client** - 5.0.0-BETA8
capabilities.setCapability("automationName", "**uiautomator2**"); - set the capability in the code

**Android Physical Device** S6, Version - 7.0

**Find Element code:**
String args = "new UiScrollable(new UiSelector().scrollable(true).instance(0)).getChildByText(new UiSelector().className("android.widget.TextView"),"Log off")";
try {
WebDriverWait wait = new WebDriverWait(driver, 5, 100);
wait.ignoring(org.openqa.selenium.NoSuchElementException.class);
wait.until(ExpectedConditions.presenceOfElementLocated(MobileBy.AndroidUIAutomator(args)));
AndroidElement element = (AndroidElement) driver.findElementByAndroidUIAutomator(args);
Main.logMessage("AndroidElement for " + locator + " found");
return element;
} catch (Exception e) {
Main.logMessage("AndroidElement " + locator + " not found");
throw new Exception("Unable to locate element: " + e);
}

**Note**: Log off button is in the end of the screen and it does scrolls down and log off button is visible in the UI (after it scrolls) but it just waits and then throws ESSocket Time out error.
Also though I pass in 5 seconds wait time webdriver wait it actually wait for longer time around 4 to 5 minutes and then throws socket time out error. I am not sure whether the issue is with the uiautomator2 or issue with wait time?

**Appium logs:**
[HTTP] <-- POST /wd/hub/session/28549bb9-8a4b-46c4-8a52-dfbb493f9501/elements 200 83 ms - 74 
[HTTP] --> POST /wd/hub/session/28549bb9-8a4b-46c4-8a52-dfbb493f9501/elements {"using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).getChildByText(new UiSelector().className(\"android.widget.TextView\"),\"Log off\")"}
[debug] [MJSONWP] Calling AppiumDriver.findElements() with args: ["-android uiautomator","new UiScrollable(new UiSelector().scrollable(true).instance(0)).getChildByText(new UiSelector().className(\"android.widget.TextView\"),\"Log off\")","28549bb9-8a4b-46c4-8a52-dfbb493f9501"]
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /elements] to [POST http://localhost:8217/wd/hub/session/f0124e6d-2b0b-4533-8c37-8d4c292baba7/elements] with body: {"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).getChildByText(new UiSelector().className(\"android.widget.TextView\"),\"Log off\")","context":"","multiple":true}
[MJSONWP] Encountered internal error running command: ProxyRequestError: Could not proxy command to remote server. Original error: Error: ESOCKETTIMEDOUT
    at JWProxy.proxy$ (../../../lib/jsonwp-proxy/proxy.js:153:13)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
[HTTP] <-- POST /wd/hub/session/28549bb9-8a4b-46c4-8a52-dfbb493f9501/elements 500 240019 ms - 251 

Please note, same code is working fine on older android versions (< 7.0) with uiautomator1. Also the wait condition works as expected in the lower versions.

I am blocked with executing tests on higher android versions due to the above issue.

**Comment by dvjana** [comment]
I am facing the same issue. This is the only blocker from switching to uiautomator2, please raise priority.

**Comment by amias-channer** [comment]
I have experienced this with Appium 1.6.5 (desktop with all updates which is  uiautomator 0.3.3) with a variety of android phones and the emulator. The rest of my tests then fail from that point onwards. Always different points and different tests.

This seems to occur after this appears in logcatl on the devices:
 channel read: DELETE /wd/hub/session/4ec86cbd-7462-4615-a97d-96bc06da99ae
06-22 12:16:56.372  5368  5632 I appium  : Delete session command
06-22 12:16:56.378  1623  2195 W AppOps  : Bad call: specified package io.appium.uiautomator2.server.test under uid 10074 but it is really 10075
06-22 12:16:56.378  5368  5632 I appium  : Stopping uiautomator2 io.appium.uiautomator2.http io.appium.uiautomator2.server
06-22 12:16:56.379  5368  5632 I appium  : AppiumResponse: {"sessionId":"4ec86cbd-7462-4615-a97d-96bc06da99ae","status":0,"value":"Session deleted"}
06-22 12:16:56.882  5368  5383 I TestRunner: finished: startServer(io.appium.uiautomator2.server.test.AppiumUiAutomator2Server)
06-22 12:16:57.028  1623  2115 I ActivityManager: Force stopping io.appium.uiautomator2.server appid=10074 user=0: finished inst
06-22 12:16:57.028  1623  2115 I ActivityManager: Killing 5368:io.appium.uiautomator2.server/u0a74 (adj 0): stop io.appium.uiautomator2.server

**Comment by amias-channer** [comment]
I noticed that both seem the OP and I seem to be using the selenium wait driver , I've read there can be issues with running the Appium and selenium web drivers at the same time, could that be it ?

**Comment by PavithraNavaneeth** [comment]
Hi @dvjana , @amias-channer 
To overcome the above issue, I used below as an alternative with appium 1.6.5 (which works fine in all android versions)
try {
       while (!waitTillVisible(driver,thisBy locator,timevalue: 5) && i<limit)
       {
                windowSwipe(driver, swipeDirection.UP);
                i++;
           }
 } catch (Exception e) {
          log("MobileElement locator not found to be scrolled");
          throw e;
}



public static Boolean waitTillVisible(AppiumDriver<MobileElement> driver, By thisBy, long timevalue)
    {
        try {
            new WebDriverWait(driver, timevalue, 100).until(ExpectedConditions.visibilityOfElementLocated(thisBy));
            return true;
        }
        catch(Exception e)
        {
            return false;
        }
    }

public static void windowSwipe(AppiumDriver<MobileElement> driver, swipeDirection thisSwipe) throws Exception
    {
        driver.context("NATIVE_APP");
        Dimension size = driver.manage().window().getSize();

        int startX = size.width / 2;
        int startY = size.height / 2;
        int leftX = (int) (size.width * 0.10);
        int righX = (int) (size.width * 0.80);
        int upY = (int) (size.height * 0.80);
        int downY = (int) (size.height * 0.10);
        TouchAction swipe = null;

        switch(thisSwipe)
        {
            case DOWN:
                swipe = new TouchAction(driver).press(startX,downY).waitAction(Duration.ofMillis(500)).moveTo(startX,upY);
                break;
            case UP:
                swipe = new TouchAction(driver).press(startX, upY).waitAction(Duration.ofMillis(500)).moveTo(startX, downY);
                break;
            case LEFT:
                swipe = new TouchAction(driver).press(righX, startY).waitAction(Duration.ofMillis(500)).moveTo(leftX, startY);
                break;
            case RIGHT:
                swipe = new TouchAction(driver).press(leftX, startY).waitAction(Duration.ofMillis(500)).moveTo(righX, startY);
                break;
        }
        swipe.release().perform();
        Main.logMessage("Swipe window completed");
    }

**Comment by cloudyhuang** [comment]
I got same issue, one element can be clicked on 1.6.5appium Uiautomator,but can't click on 1.6.5 appium Uiautomator2,and throw NosuchElementException,I dont kown why ...
Here is my element:
![f3dccfef-832e-4516-a2ba-71e1688e4b6b](https://user-images.githubusercontent.com/28583179/34372470-e918edae-eb0f-11e7-845f-4679e930d338.png)
