### ISSUE TITLE
UiSelectorSyntaxException:  Could not parse UiSelector argument: UiScrollable has no "scrollIntoView" method that takes 2 arguments

### ISSUE THREAD

**Issue by dmlemeshko** [appium/appium-uiautomator2-server#99]
Appium server: **1.7.1**
Appium client: **wd.js 1.4.1**
Env: MacOS Sierra, Android 5.0 emulator, automationName = UiAutomator2

Exception occurs if text contains **2+** commas (e.g. **1,000,000**) while trying to call `driver.elementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"1,000,000\").instance(0))")`
```
Error: [elementByAndroidUIAutomator("new UiScrollable(new UiSelector().
scrollable(true).instance(0)).scrollIntoView(newUiSelector().
textContains(\"1,000,000\").instance(0))")] 
Error response status: 9, , UnknownCommand - The requested resource could not be found,
or a request was received using an HTTP method that is not supported by the mapped
resource.
Selenium error: io.appium.uiautomator2.common.exceptions.UiSelectorSyntaxException:
Could not parse UiSelector argument: UiScrollable has no "scrollIntoView" method
that takes 2 arguments
	at io.appium.uiautomator2.handler.FindElement.findByUiAutomator(FindElement.java:194)
	at io.appium.uiautomator2.handler.FindElement.findElement(FindElement.java:155)
	at io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:102)
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:56)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:202)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:193)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by idxn** [comment]
I experienced the same issue.

**Comment by Steve-Liu** [comment]
any follow up to this issue?

**Comment by imurchie** [comment]
This is fixed.

**Comment by idxn** [comment]
Yes! Finally :)
